version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - '4200:80'
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
